apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: gemini-hpa
  namespace: gemini-namespace
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: gemini
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 40
